# Generated by Django 2.2.3 on 2020-04-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retweets', models.IntegerField()),
                ('tweet', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'Tweets',
            },
        ),
    ]
