# Generated by Django 2.2.3 on 2020-04-23 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweets',
            old_name='retweets',
            new_name='retweet_count',
        ),
    ]
