# Generated by Django 2.2.3 on 2020-04-28 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_auto_20200423_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='created_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='tweets',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweets',
            name='location',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweets',
            name='source',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
    ]
